name: JSON Schema Code Convention
on:
  push:
    branches: 
      - main
jobs:
  json_linter_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start JSON Linter
        run: | 
          npm i -g @prantlf/jsonlint
          jsonlint $GITHUB_WORKSPACE/.github/workflows/JSON_DetailedDataSchema_Example.json
