name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: PrintLanguageVersions
    steps:
      - name: Download and Install MongoDB
        run: |
          wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-5.0.5.tgz -O mongodb.tgz
          tar -xzf mongodb.tgz
          sudo mv mongodb-linux-x86_64-ubuntu2004-5.0.5/bin/* /usr/local/bin/
          rm -rf mongodb.tgz mongodb-linux-x86_64-ubuntu2004-5.0.5
      - name: Print PostgreSQL Version
        run: psql --version
